accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup_view, name="signup"),
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout"),
]

articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
    path('', views.article_list, name="list"),
    path('create/', views.article_create, name="create"),
    path('(<slug:slug>/', views.article_detail, name="detail"),
]

djangonautic/urls.py
from django.urls import path, include
from django.contrib import admin
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from articles import views as article_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
    path('about/', views.about),
    path('', article_views.article_list, name="home"),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

articles/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Article(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    thumb = models.ImageField(default='default.png', blank=True)
    author = models.ForeignKey(User, default=None,  on_delete=models.CASCADE,)

    def __str__(self):
        return self.title

    def snippet(self):
        return self.body[:50] + '...'


# CASCADE: When the referenced object is deleted, also delete the objects that have references to it (when you remove a blog post for instance, you might want to delete comments as well). SQL equivalent: CASCADE.
# PROTECT: Forbid the deletion of the referenced object. To delete it you will have to delete all objects that reference it manually. SQL equivalent: RESTRICT.
# SET_NULL: Set the reference to NULL (requires the field to be nullable). For instance, when you delete a User, you might want to keep the comments he posted on blog posts, but say it was posted by an anonymous (or deleted) user. SQL equivalent: SET NULL.
# SET_DEFAULT: Set the default value. SQL equivalent: SET DEFAULT.
# SET(...): Set a given value. This one is not part of the SQL standard and is entirely handled by Django.
# DO_NOTHING: Probably a very bad idea since this would create integrity issues in your database (referencing an object that actually doesn't exist). SQL equivalent: NO ACTION.

articles/forms.py
from django import forms
from . import models


class CreateArticle(forms.ModelForm):
    class Meta:
        model = models.Article
        fields = ['title', 'body', 'slug', 'thumb', ]

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout

def signup_view(request):
    if request.method == 'POST':
         form = UserCreationForm(request.POST)
         if form.is_valid():
             user = form.save()
             #  log the user in
             login(request, user)
             return redirect('articles:list')
    else:
        form = UserCreationForm()
    return render(request, 'accounts/signup.html', { 'form': form })

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            # log the user in
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
               return redirect('articles:list')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', { 'form': form })

def logout_view(request):
    if request.method == 'POST':
            logout(request)
            return redirect('articles:list')

articles/views.py
from django.http import HttpResponse, Http404
from django.shortcuts import render, redirect
from .models import Article
from django.contrib.auth.decorators import login_required
from . import forms


def article_list(request):
    articles = Article.objects.all().order_by('date')
    return render(request, 'articles/article_list.html', {'articles': articles})


def article_detail(request, slug):
    try:
        # return HttpResponse(slug)
        article = Article.objects.get(slug=slug)
    except Article.DoesNotExist:
        raise Http404("Not Found")
    return render(request, 'articles/article_detail.html', {'article': article})


@login_required(login_url="/accounts/login/")
def article_create(request):
    if request.method == 'POST':
        form = forms.CreateArticle(request.POST, request.FILES)
        if form.is_valid():
            # save article to db
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
            return redirect('articles:list')
    else:
        form = forms.CreateArticle()
    return render(request, 'articles/article_create.html', {'form': form})

djangonautic/views.py
from django.http import HttpResponse
from django.shortcuts import render

def homepage(request):
    # return HttpResponse('homepage')
    return render(request, 'homepage.html')

def about(request):
    # return HttpResponse('about')
    return render(request, 'about.html')

accounts/templates/accounts/login.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1>Log in</h1>
    <form class="site-form" action="{% url 'accounts:login' %}" method="post">
        {% csrf_token %}
        {{ form }}
        {% if request.GET.next %}
            <input type="hidden" name="next" value="{{ request.GET.next }}" />
        {% endif %}
        <input type="submit" value="Login" />
    </form>
    <p>Not got an account? <a href="{% url 'accounts:signup' %}">Sign Up</a></p>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1>Signup</h1>
    <form class="site-form" action="{% url 'accounts:signup' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Signup">
    </form>
{% endblock %}

articles/templates/articles/article_create.html
{% extends 'base_layout.html' %}

{% block content %}
    <div class="create-article">
        <h2>Create an Awesome New Article</h2>
        <form class="site-form" action="{% url 'articles:create' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="Create">
        </form>
    </div>
    <script src="/static/slugify.js"></script>
{% endblock %}

articles/templates/articles/article_detail.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="article-detail">
    <div class="article">
        <img src="{{ article.thumb.url }}" />
        <h2>{{ article.title }}</h2>
        <h3>Written by {{ article.author.username }}</h3>
        <p>{{ article.body }}</p>
        <p>{{ article.date }}</p>
    </div>
</div>
{% endblock %}

articles/templates/articles/article_list.html
{% extends 'base_layout.html' %}

{% block content%}
    <h1>Articles List</h1>
    <div class="articles">
    {% for article in articles %}
        <div class="article">
            <h2><a href="{% url 'articles:detail' slug=article.slug %}">{{ article.title }}</a></h2>
            <p>{{ article.snippet }}</p>
            <p>{{ article.date }}</p>
            <p class="author">added by {{ article.author.username }}</p>
        </div>
    {% endfor %}
    </div>
{% endblock %}

templates/about.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="wrapper">
    <h1>About Us</h1>
    <p>We like django.</p>
</div>
{% endblock %}

templates/base_layout.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Djangonauts</title>
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="{% static 'favicon' %}" type="image/gif" sizes="16x16">
</head>

<body>
    <header class="wrapper">
        <h1><a href="{% url 'home' %}"><img src="{% static 'logo.png' %}" alt="djangonautic" /></a></h1>
        <nav>
            <ul>
                {% if user.is_authenticated %}
                <li>
                    <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
                        {% csrf_token %}
                        <button type="submit">Logout</button>
                    </form>
                </li>
                <li><a href="{% url 'articles:create' %}" class="highlight">New Article</a></li>
                {% else %}
                <li><a href="{% url 'accounts:login' %}">Login</a></li>
                <li><a href="{% url 'accounts:signup' %}">Signup</a></li>
                {% endif %}
            </ul>
        </nav>
    </header>
    <div class="wrapper">
        {% block content %}
        {% endblock %}
    </div>
</body>

</html>